services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #核心：自动获取当前运行脚本的 Linux 用户的 UID 和 GID 传给 Docker
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    # 动态引用 .env 中的镜像名称和版本号
    image: ${APP_IMAGE_NAME:-fast_api_app}:${APP_VERSION:-latest}
    # 动态引用 .env 中的容器名称
    container_name: ${APP_CONTAINER_NAME:-fast_api_app}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app:/workspace/app
    environment:
      - ENV=production
      - TZ=Asia/Shanghai
